# CMake generated Testfile for 
# Source directory: /home/leggedrobot/Documents/GitHub/go1-ws1/mujoco_mpc/mjpc/test/gradient_planner
# Build directory: /home/leggedrobot/Documents/GitHub/go1-ws1/mujoco-mpc-mjpc-build/test/gradient_planner
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(GradientPlannerTest.Particle "/home/leggedrobot/Documents/GitHub/go1-ws1/mujoco-mpc-mjpc-build/bin/gradient_planner_test" "--gtest_filter=GradientPlannerTest.Particle")
set_tests_properties(GradientPlannerTest.Particle PROPERTIES  WORKING_DIRECTORY "/home/leggedrobot/Documents/GitHub/go1-ws1/mujoco_mpc/mjpc/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.22/Modules/GoogleTest.cmake;400;add_test;/home/leggedrobot/Documents/GitHub/go1-ws1/mujoco_mpc/mjpc/test/CMakeLists.txt;31;gtest_add_tests;/home/leggedrobot/Documents/GitHub/go1-ws1/mujoco_mpc/mjpc/test/gradient_planner/CMakeLists.txt;15;test;/home/leggedrobot/Documents/GitHub/go1-ws1/mujoco_mpc/mjpc/test/gradient_planner/CMakeLists.txt;0;")
add_test(GradientTest.Gradient "/home/leggedrobot/Documents/GitHub/go1-ws1/mujoco-mpc-mjpc-build/bin/gradient_test" "--gtest_filter=GradientTest.Gradient")
set_tests_properties(GradientTest.Gradient PROPERTIES  WORKING_DIRECTORY "/home/leggedrobot/Documents/GitHub/go1-ws1/mujoco_mpc/mjpc/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.22/Modules/GoogleTest.cmake;400;add_test;/home/leggedrobot/Documents/GitHub/go1-ws1/mujoco_mpc/mjpc/test/CMakeLists.txt;31;gtest_add_tests;/home/leggedrobot/Documents/GitHub/go1-ws1/mujoco_mpc/mjpc/test/gradient_planner/CMakeLists.txt;18;test;/home/leggedrobot/Documents/GitHub/go1-ws1/mujoco_mpc/mjpc/test/gradient_planner/CMakeLists.txt;0;")
add_test(GradientTest.ZeroTest "/home/leggedrobot/Documents/GitHub/go1-ws1/mujoco-mpc-mjpc-build/bin/zero_test" "--gtest_filter=GradientTest.ZeroTest")
set_tests_properties(GradientTest.ZeroTest PROPERTIES  WORKING_DIRECTORY "/home/leggedrobot/Documents/GitHub/go1-ws1/mujoco_mpc/mjpc/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.22/Modules/GoogleTest.cmake;400;add_test;/home/leggedrobot/Documents/GitHub/go1-ws1/mujoco_mpc/mjpc/test/CMakeLists.txt;31;gtest_add_tests;/home/leggedrobot/Documents/GitHub/go1-ws1/mujoco_mpc/mjpc/test/gradient_planner/CMakeLists.txt;26;test;/home/leggedrobot/Documents/GitHub/go1-ws1/mujoco_mpc/mjpc/test/gradient_planner/CMakeLists.txt;0;")
add_test(GradientTest.LinearTest "/home/leggedrobot/Documents/GitHub/go1-ws1/mujoco-mpc-mjpc-build/bin/linear_test" "--gtest_filter=GradientTest.LinearTest")
set_tests_properties(GradientTest.LinearTest PROPERTIES  WORKING_DIRECTORY "/home/leggedrobot/Documents/GitHub/go1-ws1/mujoco_mpc/mjpc/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.22/Modules/GoogleTest.cmake;400;add_test;/home/leggedrobot/Documents/GitHub/go1-ws1/mujoco_mpc/mjpc/test/CMakeLists.txt;31;gtest_add_tests;/home/leggedrobot/Documents/GitHub/go1-ws1/mujoco_mpc/mjpc/test/gradient_planner/CMakeLists.txt;29;test;/home/leggedrobot/Documents/GitHub/go1-ws1/mujoco_mpc/mjpc/test/gradient_planner/CMakeLists.txt;0;")
add_test(GradientTest.CubicTest "/home/leggedrobot/Documents/GitHub/go1-ws1/mujoco-mpc-mjpc-build/bin/cubic_test" "--gtest_filter=GradientTest.CubicTest")
set_tests_properties(GradientTest.CubicTest PROPERTIES  WORKING_DIRECTORY "/home/leggedrobot/Documents/GitHub/go1-ws1/mujoco_mpc/mjpc/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.22/Modules/GoogleTest.cmake;400;add_test;/home/leggedrobot/Documents/GitHub/go1-ws1/mujoco_mpc/mjpc/test/CMakeLists.txt;31;gtest_add_tests;/home/leggedrobot/Documents/GitHub/go1-ws1/mujoco_mpc/mjpc/test/gradient_planner/CMakeLists.txt;32;test;/home/leggedrobot/Documents/GitHub/go1-ws1/mujoco_mpc/mjpc/test/gradient_planner/CMakeLists.txt;0;")
